language: node_js
node_js:
- 13.2
deploy:
  provider: s3
  cleanup: true
  skip_cleanup: true
  access_key_id: AKIAZIUCQ6FCCBH6336J
  secret_access_key:
    secure: Drl3jBRVy/TXqthS/jZCTdKJFHvdRZ9Cqp9DFlHREoMyIzmYd+sLJXGNKaRxD8OOZcwUzwH07hTdPk4uQ2VEuO6GC9lrFAVsy0M1PbiOgxW+CsSc31GiIdEiJ6383BdyIJLysi7qDjO3eCQodWiZpcbNGJGRIilfQXYvgLs7/X9TmeAHGu4fFAyXr4zBgMguEQzahvcZq1xYgPhYuyI0g5a9AbTpQLSL8R5kqZGtcyiqPew8zitQuMNPlumnZ0j/P011gS3szJnCuEExYPETcHFfWcFeN/ZbtXKzdVx4X6ezoaoMaEJHqAkPxUzweG00aSqWMPpXORF5wPAKWLMF6MOMph+RdkSzNI2ue5+z1HIcDwKpU68TxREA13c552gl3T2u3s/+BIZZMtfYhDi8br9sWruc5y6UzGL9uiitd/woKY7uk98LhL0NURP8/cZ0yHNQ7CV0r8FL0UUeZnUlkvqbEs8tmO8NCavg5H3KM7fCDnOVvKQZDmOnctyxy+jv/PjPe3q8HQo/K+61zLs6i2qu7OAz9D2gw6t4bt1ryKmkCt/nROUuUONhvHAphli1VYDSWthFgtemIKRbHKW8gB1FrE9BF1WXA+i7DUjGNdnTD1NyoEpBwb2Am3NsFvG7tPGAot4t5mJLdPsTJWlQGRfjN4zHqrU1XSL1o0BFGmU=
  bucket: alpheios-grammars
  region: us-east-2
  local_dir: "."
  upload_dir: bennett
  acl: public_read
  cache_control: max-age=604800
  on:
    repo: alpheios-project/grammar-bennett
    branch: production
