language: node_js
node_js:
- 13.2
deploy:
  provider: s3
  cleanup: true
  skip_cleanup: true
  access_key_id: 
  secret_access_key: AKIAZIUCQ6FCCBH6336J
    secure: sRhd1qse8mxnXySZzKftJARSb/DW9p3iSYF27b1JRZCa7x3R6Fw/6aVWUvI8F068+PKnbu/w2N8IueaBD+YI1ov3534khOScz7QLGfxdvt7d8vJw6DbHfFiMySfkz5UWK6JjRq/yY1bRR0gRj2/nBypG0rOzMfPvwFxxs3FLR3INEWFPDko2kDG2TWyAFxfU0/vcn92wi2UEw5CossiSjtC03luAJAj6tCEFG8MCSz1cR/IrwIJWC4k7W976u4v4Ms+P7IPQgal+41cuGtvUSowIINhDlBo+8eBmlSQrcUXHMfNVY4v6FhJwFy/BU/nNleHXHt2+H4jaUoGmO4lhAMQLBMZFAldEZN4o1ZgvHXO+mnPlMZp1wLIu+ZJDgFxmNSInsNTpWN0hutjkR6CC6+joJ10FEUZXTvrESCHMWoq8R2j277pwYBNqi5UfccngOTOYlhSVYygk3BoQ6J+t1iCTJP8vxJ2+t0zZ3sYJ8c6+FBtOF7IUlSRZFMwq/+qeK40yhjDNRWW6FQMFCtck6LvA/vvTIuRamwGUErjHG5jkZ4qdFkIG/fd5dZEffiKPzA9tOUOG+spzRDTIYWYDYZFy059CT+r6PpNoKNEiQRC9irCOWSNH0zOEIYdtxsbgQIeaAfMOKnQq6rduWyD36LZ4EYucuyE2SqvJ1H8QZ8s=
  bucket: alpheios-grammars
  region: us-east-2
  local_dir: .
  upload_dir: bennett
  acl: public_read
  cache_control: max-age=15552000
  on:
    repo: alpheios-project/grammar-bennett
    branch: master
