language: node_js
node_js:
- 13.2
deploy:
  provider: s3
  cleanup: true
  skip_cleanup: true
  access_key_id: AKIAZIUCQ6FCOQLJIBPD
  secret_access_key:
    secure: "oy9jyfNWP0YruWe4J6EsF6CdAuUOPbVQ2PHeWNunr2VcbgQDd/WbjBBqs69vBO9Z+feG1Bc/QYVKbNWBBHwe1d4C8ywr0ZJXAWhMFNnAb4ZZviKBznZjWHy8CUH+LRGHZH8JQ5NNXYZY42c7CkNd7dA8lTEsTuOyqTSjw2MQp7UABT8GXwVYGJGLv1/fCQCSia0sMQJMAUYMYZFSLwHkSBnCn7qmbY/y/bAj38IBrHjXDwZ8oi/MGthaCESBMyx8/xPvuaHEnkL4ricGlr5Ud/D+DTUMr8e78fwl6WuIdDkajHzuBh9A3G9h/2jmmaJnnQyI4lpr7gHzNs+GcUUhp+BSpxxlX0p98RrrYMeL/ckK2KVQi0EjHiJsJUbOmHfKijnyrkoJ5p6grp6OxyFsdDWDS/J+wGpzJgEm1RNwknDG23S+szrir0z6UT27DinzurVnVOHFuEzfNAh/Rm758kWZyoeTH7oZt94eDPiU5SdTTP0C8LFY6bnYdkVDCvWWTDrH5S8NebnQuy43sd0nxe78OkQLAfpJmIBcr31RTM7Ctu/mRxQJkXilrY4uNDANFlR6VnkTPnPrAK7k3QkiDLulZSFMH3o7vTJKYyyZTwbY2NEVVUnoSxdLGEyIu3rUS5cTNqQz1D9zdYgMr0+HNBBX2XWmtmu4dr0w476W9R4="
  bucket: alpheios-grammars
  region: us-east-2
  local_dir: "."
  upload_dir: bennett
  acl: public_read
  cache_control: max-age=15552000
  on:
    repo: alpheios-project/grammar-bennett
    branch: master
